/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmenttwo;

import java.util.Arrays;


/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  private void sunPlanetMoon() {

    assignmenttwo.solitares.Star sun = new assignmenttwo.solitares.Star("Sun", 696342);

    // printing the Solar System
    System.out.println("Solar System:");
    System.out.println("  " + sun); // print the star (Sun)

    // Creating an array to hold the planets
    assignmenttwo.solitares.Planet[] planets = {
        new assignmenttwo.solitares.Planet("Mercury", 2439),
        new assignmenttwo.solitares.Planet("Venus", 6051),
        new assignmenttwo.solitares.Planet("Earth", 6371),
        new assignmenttwo.solitares.Planet("Mars", 3389),
        new assignmenttwo.solitares.Planet("Jupiter", 69911),
        new assignmenttwo.solitares.Planet("Saturn", 58232),
        new assignmenttwo.solitares.Planet("Uranus", 25362),
        new assignmenttwo.solitares.Planet("Neptune", 24622)
      };

    System.out.println("\n  Planets:");
    for (assignmenttwo.solitares.Planet planet : planets) {
      System.out.println("    " + planet); // print each planet
    }

    // creating an array to hold some moons
    assignmenttwo.solitares.Moon[] moons = {
        new assignmenttwo.solitares.Moon("Moon", 1737),
        new assignmenttwo.solitares.Moon("Phobos", 12),
        new assignmenttwo.solitares.Moon("Io", 1821),
        new assignmenttwo.solitares.Moon("Europa", 1560),
        new assignmenttwo.solitares.Moon("Ganymede", 2634),
        new assignmenttwo.solitares.Moon("Callisto", 2410),
        new assignmenttwo.solitares.Moon("Mimas", 198),
        new assignmenttwo.solitares.Moon("Enceladus", 252),
        new assignmenttwo.solitares.Moon("Tethys", 533),
        new assignmenttwo.solitares.Moon("Dione", 561),
        new assignmenttwo.solitares.Moon("Rhea", 764),
        new assignmenttwo.solitares.Moon("Titan", 2575)
      };

    System.out.println("\n  Some moons:");
    for (assignmenttwo.solitares.Moon moon : moons) {
      System.out.println("    " + moon); // print each moon
    }
  }

  private void heavenlyBody() {
    assignmenttwo.refactoredsolitares.Star sun = 
        new assignmenttwo.refactoredsolitares.Star("Sun", 696342);

    // printing the Solar System
    System.out.println("Solar System:");
    System.out.println("  " + sun); // print the star (Sun)

    // Creating an array to hold the planets
    assignmenttwo.refactoredsolitares.Planet[] planets = {
        new assignmenttwo.refactoredsolitares.Planet("Mercury", 2439),
        new assignmenttwo.refactoredsolitares.Planet("Venus", 6051),
        new assignmenttwo.refactoredsolitares.Planet("Earth", 6371),
        new assignmenttwo.refactoredsolitares.Planet("Mars", 3389),
        new assignmenttwo.refactoredsolitares.Planet("Jupiter", 69911),
        new assignmenttwo.refactoredsolitares.Planet("Saturn", 58232),
        new assignmenttwo.refactoredsolitares.Planet("Uranus", 25362),
        new assignmenttwo.refactoredsolitares.Planet("Neptune", 24622)
      };

    System.out.println("\n  Planets:");
    for (assignmenttwo.refactoredsolitares.Planet planet : planets) {
      System.out.println("    " + planet); // print each planet
    }

    // creating an array to hold some moons
    assignmenttwo.refactoredsolitares.Moon[] moons = {
        new assignmenttwo.refactoredsolitares.Moon("Moon", 1737),
        new assignmenttwo.refactoredsolitares.Moon("Phobos", 12),
        new assignmenttwo.refactoredsolitares.Moon("Io", 1821),
        new assignmenttwo.refactoredsolitares.Moon("Europa", 1560),
        new assignmenttwo.refactoredsolitares.Moon("Ganymede", 2634),
        new assignmenttwo.refactoredsolitares.Moon("Callisto", 2410),
        new assignmenttwo.refactoredsolitares.Moon("Mimas", 198),
        new assignmenttwo.refactoredsolitares.Moon("Enceladus", 252),
        new assignmenttwo.refactoredsolitares.Moon("Tethys", 533),
        new assignmenttwo.refactoredsolitares.Moon("Dione", 561),
        new assignmenttwo.refactoredsolitares.Moon("Rhea", 764),
        new assignmenttwo.refactoredsolitares.Moon("Titan", 2575)
      };

    System.out.println("\n  Some moons:");
    for (assignmenttwo.refactoredsolitares.Moon moon : moons) {
      System.out.println("    " + moon); // print each moon
    }
  }

  private assignmenttwo.solarsystem.Star solarSytem() {
    assignmenttwo.solarsystem.Star star = new assignmenttwo.solarsystem.Star("Sun", 696342);
    assignmenttwo.solarsystem.Planet p1 =  star.addPlanet("earth", 6371, 6371000);
    p1.addMoon("moon", 1737, 1737000);

    assignmenttwo.solarsystem.Planet p2 = star.addPlanet("mars", 3389, 3389000);
    p2.addMoon("phobos", 12, 12000);
    p2.addMoon("deimos", 6, 6000);

    assignmenttwo.solarsystem.Planet p3 = star.addPlanet("jupiter", 69911, 69911000);
    p3.addMoon("io", 1821, 1821000);
    p3.addMoon("europa", 1560, 1560000);
    p3.addMoon("ganymede", 2634, 2634000);
    p3.addMoon("callisto", 2410, 2410000);

    assignmenttwo.solarsystem.Planet p4 = star.addPlanet("saturn", 58232, 58232000);
    p4.addMoon("mimas", 198, 198000);
    p4.addMoon("encceladus", 252, 252000);
    p4.addMoon("tethys", 533, 533000);
    p4.addMoon("dione", 561, 561000);
    p4.addMoon("rhea", 764, 764000);
    p4.addMoon("titan", 2575, 2575000);
    return star;
  }

  private void printHeavenlybodies(assignmenttwo.solarsystem.Star star) {
    assignmenttwo.solarsystem.HeavenlyBody[] allHeavenlyBodies = star.getHeavenlyBodies();
    for (assignmenttwo.solarsystem.HeavenlyBody currentHeavenlyBody : allHeavenlyBodies) {
      System.out.println(currentHeavenlyBody.toString());
      
    }
  }

  private void orderInHeaven(assignmenttwo.solarsystem.Star star) {     

    assignmenttwo.solarsystem.HeavenlyBody[] allHeavenlyBodies = star.getHeavenlyBodies();
    Arrays.sort(allHeavenlyBodies);
    for (assignmenttwo.solarsystem.HeavenlyBody currentHeavenlyBody : allHeavenlyBodies) {
      System.out.println(currentHeavenlyBody.toString());
      
    }
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    theApp.sunPlanetMoon();
    theApp.heavenlyBody();
    assignmenttwo.solarsystem.Star star = theApp.solarSytem();
    theApp.printHeavenlybodies(star);
    System.out.println("///////////////////////////////////////////////////" 
        + "////////////////////////////////////////////");
    theApp.orderInHeaven(star);

  }
}
